// Re-export all shared types for dashboard usage
export type {
  Environment,
  HealthStatus,
  DeployStatus,
  EnvironmentState,
  Project,
  DeployEntry,
  BuildArtifact,
  Notification,
  ServiceCheck,
  DnsRecord,
  WorkflowRun,
  PullRequest,
  ProjectsResponse,
  ProjectDetailResponse,
  DeploysResponse,
  NotificationsResponse,
  SystemStatusResponse,
  BranchesResponse,
  PullRequestsResponse,
  DnsRecordsResponse,
  BuildsResponse,
  FilesResponse,
} from "@veriel-ops/shared";
