import type {
  Project,
  DeployEntry,
  BuildArtifact,
  SystemStats,
} from "./types";

export const projects: Project[] = [
  {
    name: "streamvault",
    type: "astro-ssr",
    repo: "veriel-cloud/streamvault",
    domain: "streamvault.veriel.dev",
    customDomain: false,
    coverage: 87.3,
    coverageThreshold: 80,
    environments: {
      des: {
        version: "dev-a3f21c4",
        commitSha: "a3f21c4",
        url: "https://dev.streamvault.veriel.dev",
        status: "healthy",
        lastDeployAt: "2026-03-22T09:15:00Z",
      },
      pre: {
        version: "0.4.0",
        commitSha: "e7b92d1",
        url: "https://pre.streamvault.veriel.dev",
        status: "healthy",
        lastDeployAt: "2026-03-21T16:30:00Z",
      },
      pro: {
        version: "0.3.2",
        commitSha: "c1d8f3a",
        url: "https://streamvault.veriel.dev",
        status: "healthy",
        lastDeployAt: "2026-03-20T10:00:00Z",
      },
    },
    createdAt: "2026-01-15T00:00:00Z",
  },
  {
    name: "whybroke",
    type: "react-spa",
    repo: "veriel-cloud/whybroke",
    domain: "whybroke.veriel.dev",
    customDomain: false,
    coverage: 92.1,
    coverageThreshold: 80,
    environments: {
      des: {
        version: "dev-f82bc01",
        commitSha: "f82bc01",
        url: "https://dev.whybroke.veriel.dev",
        status: "healthy",
        lastDeployAt: "2026-03-22T11:45:00Z",
      },
      pre: {
        version: "1.1.0",
        commitSha: "d49ae72",
        url: "https://pre.whybroke.veriel.dev",
        status: "healthy",
        lastDeployAt: "2026-03-22T08:20:00Z",
      },
      pro: {
        version: "1.0.2",
        commitSha: "b83fc12",
        url: "https://whybroke.veriel.dev",
        status: "healthy",
        lastDeployAt: "2026-03-19T14:00:00Z",
      },
    },
    createdAt: "2026-02-01T00:00:00Z",
  },
  {
    name: "contentforge",
    type: "astro-static",
    repo: "veriel-cloud/contentforge",
    domain: "contentforge.veriel.dev",
    customDomain: false,
    coverage: 74.5,
    coverageThreshold: 80,
    environments: {
      des: {
        version: "dev-1a2b3c4",
        commitSha: "1a2b3c4",
        url: "https://dev.contentforge.veriel.dev",
        status: "healthy",
        lastDeployAt: "2026-03-22T12:00:00Z",
      },
      pre: {
        version: null,
        commitSha: null,
        url: "https://pre.contentforge.veriel.dev",
        status: "idle",
        lastDeployAt: null,
      },
      pro: {
        version: null,
        commitSha: null,
        url: "https://contentforge.veriel.dev",
        status: "idle",
        lastDeployAt: null,
      },
    },
    createdAt: "2026-03-10T00:00:00Z",
  },
  {
    name: "report-pilot",
    type: "astro-ssr",
    repo: "veriel-cloud/report-pilot",
    domain: "reportpilot.com",
    customDomain: true,
    coverage: 88.9,
    coverageThreshold: 80,
    environments: {
      des: {
        version: "dev-9c8d7e6",
        commitSha: "9c8d7e6",
        url: "https://dev.reportpilot.com",
        status: "healthy",
        lastDeployAt: "2026-03-21T18:30:00Z",
      },
      pre: {
        version: "2.1.0",
        commitSha: "5f4e3d2",
        url: "https://pre.reportpilot.com",
        status: "healthy",
        lastDeployAt: "2026-03-21T15:00:00Z",
      },
      pro: {
        version: "2.0.1",
        commitSha: "a1b2c3d",
        url: "https://reportpilot.com",
        status: "degraded",
        lastDeployAt: "2026-03-18T09:00:00Z",
      },
    },
    createdAt: "2025-11-20T00:00:00Z",
  },
  {
    name: "glass-box",
    type: "backend-worker",
    repo: "veriel-cloud/glass-box",
    domain: "glass-box.veriel.dev",
    customDomain: false,
    coverage: 81.2,
    coverageThreshold: 80,
    environments: {
      des: {
        version: "dev-bb44cc5",
        commitSha: "bb44cc5",
        url: "https://dev.glass-box.veriel.dev",
        status: "healthy",
        lastDeployAt: "2026-03-22T07:00:00Z",
      },
      pre: {
        version: "0.2.0",
        commitSha: "aa33bb4",
        url: "https://pre.glass-box.veriel.dev",
        status: "healthy",
        lastDeployAt: "2026-03-20T12:00:00Z",
      },
      pro: {
        version: "0.1.1",
        commitSha: "ff22ee3",
        url: "https://glass-box.veriel.dev",
        status: "healthy",
        lastDeployAt: "2026-03-15T10:00:00Z",
      },
    },
    createdAt: "2026-02-28T00:00:00Z",
  },
];

export const deploys: DeployEntry[] = [
  {
    id: "dpl-001",
    project: "whybroke",
    environment: "des",
    version: "dev-f82bc01",
    commitSha: "f82bc01",
    branch: "develop",
    timestamp: "2026-03-22T11:45:00Z",
    coverage: 92.1,
    duration: 34,
    action: "deploy",
    triggeredBy: "github-actions",
    status: "success",
  },
  {
    id: "dpl-002",
    project: "contentforge",
    environment: "des",
    version: "dev-1a2b3c4",
    commitSha: "1a2b3c4",
    branch: "develop",
    timestamp: "2026-03-22T12:00:00Z",
    coverage: 74.5,
    duration: 28,
    action: "deploy",
    triggeredBy: "github-actions",
    status: "success",
  },
  {
    id: "dpl-003",
    project: "streamvault",
    environment: "des",
    version: "dev-a3f21c4",
    commitSha: "a3f21c4",
    branch: "develop",
    timestamp: "2026-03-22T09:15:00Z",
    coverage: 87.3,
    duration: 41,
    action: "deploy",
    triggeredBy: "github-actions",
    status: "success",
  },
  {
    id: "dpl-004",
    project: "whybroke",
    environment: "pre",
    version: "1.1.0",
    commitSha: "d49ae72",
    branch: "release/1.1.0",
    timestamp: "2026-03-22T08:20:00Z",
    coverage: 92.1,
    duration: 38,
    action: "deploy",
    triggeredBy: "github-actions",
    status: "success",
  },
  {
    id: "dpl-005",
    project: "streamvault",
    environment: "pre",
    version: "0.4.0",
    commitSha: "e7b92d1",
    branch: "release/0.4.0",
    timestamp: "2026-03-21T16:30:00Z",
    coverage: 87.3,
    duration: 45,
    action: "deploy",
    triggeredBy: "github-actions",
    status: "success",
  },
  {
    id: "dpl-006",
    project: "report-pilot",
    environment: "pre",
    version: "2.1.0",
    commitSha: "5f4e3d2",
    branch: "release/2.1.0",
    timestamp: "2026-03-21T15:00:00Z",
    coverage: 88.9,
    duration: 52,
    action: "deploy",
    triggeredBy: "github-actions",
    status: "success",
  },
  {
    id: "dpl-007",
    project: "report-pilot",
    environment: "des",
    version: "dev-9c8d7e6",
    commitSha: "9c8d7e6",
    branch: "develop",
    timestamp: "2026-03-21T18:30:00Z",
    coverage: 88.9,
    duration: 39,
    action: "deploy",
    triggeredBy: "github-actions",
    status: "success",
  },
  {
    id: "dpl-008",
    project: "streamvault",
    environment: "pro",
    version: "0.3.2",
    commitSha: "c1d8f3a",
    branch: "main",
    timestamp: "2026-03-20T10:00:00Z",
    coverage: 87.3,
    duration: 48,
    action: "deploy",
    triggeredBy: "github-actions",
    status: "success",
  },
  {
    id: "dpl-009",
    project: "glass-box",
    environment: "pre",
    version: "0.2.0",
    commitSha: "aa33bb4",
    branch: "release/0.2.0",
    timestamp: "2026-03-20T12:00:00Z",
    coverage: 81.2,
    duration: 22,
    action: "deploy",
    triggeredBy: "github-actions",
    status: "success",
  },
  {
    id: "dpl-010",
    project: "whybroke",
    environment: "pro",
    version: "1.0.2",
    commitSha: "b83fc12",
    branch: "main",
    timestamp: "2026-03-19T14:00:00Z",
    coverage: 91.8,
    duration: 36,
    action: "deploy",
    triggeredBy: "github-actions",
    status: "success",
  },
  {
    id: "dpl-011",
    project: "report-pilot",
    environment: "pro",
    version: "2.0.1",
    commitSha: "a1b2c3d",
    branch: "main",
    timestamp: "2026-03-18T09:00:00Z",
    coverage: 88.2,
    duration: 55,
    action: "rollback",
    triggeredBy: "veriel-dev",
    status: "success",
  },
  {
    id: "dpl-012",
    project: "glass-box",
    environment: "pro",
    version: "0.1.1",
    commitSha: "ff22ee3",
    branch: "main",
    timestamp: "2026-03-15T10:00:00Z",
    coverage: 81.2,
    duration: 19,
    action: "deploy",
    triggeredBy: "github-actions",
    status: "success",
  },
];

export const buildArtifacts: BuildArtifact[] = [
  {
    name: "v0.4.0_e7b92d1.tar.gz",
    project: "streamvault",
    environment: "pre",
    version: "0.4.0",
    commitSha: "e7b92d1",
    size: "4.2 MB",
    timestamp: "2026-03-21T16:30:00Z",
    coverage: 87.3,
  },
  {
    name: "v0.3.2_c1d8f3a.tar.gz",
    project: "streamvault",
    environment: "pro",
    version: "0.3.2",
    commitSha: "c1d8f3a",
    size: "4.1 MB",
    timestamp: "2026-03-20T10:00:00Z",
    coverage: 87.3,
  },
  {
    name: "v1.1.0_d49ae72.tar.gz",
    project: "whybroke",
    environment: "pre",
    version: "1.1.0",
    commitSha: "d49ae72",
    size: "2.8 MB",
    timestamp: "2026-03-22T08:20:00Z",
    coverage: 92.1,
  },
  {
    name: "v1.0.2_b83fc12.tar.gz",
    project: "whybroke",
    environment: "pro",
    version: "1.0.2",
    commitSha: "b83fc12",
    size: "2.7 MB",
    timestamp: "2026-03-19T14:00:00Z",
    coverage: 91.8,
  },
  {
    name: "v2.1.0_5f4e3d2.tar.gz",
    project: "report-pilot",
    environment: "pre",
    version: "2.1.0",
    commitSha: "5f4e3d2",
    size: "5.6 MB",
    timestamp: "2026-03-21T15:00:00Z",
    coverage: 88.9,
  },
  {
    name: "v2.0.1_a1b2c3d.tar.gz",
    project: "report-pilot",
    environment: "pro",
    version: "2.0.1",
    commitSha: "a1b2c3d",
    size: "5.4 MB",
    timestamp: "2026-03-18T09:00:00Z",
    coverage: 88.2,
  },
  {
    name: "v0.2.0_aa33bb4.tar.gz",
    project: "glass-box",
    environment: "pre",
    version: "0.2.0",
    commitSha: "aa33bb4",
    size: "1.1 MB",
    timestamp: "2026-03-20T12:00:00Z",
    coverage: 81.2,
  },
  {
    name: "v0.1.1_ff22ee3.tar.gz",
    project: "glass-box",
    environment: "pro",
    version: "0.1.1",
    commitSha: "ff22ee3",
    size: "1.0 MB",
    timestamp: "2026-03-15T10:00:00Z",
    coverage: 81.2,
  },
];

export const systemStats: SystemStats = {
  totalProjects: projects.length,
  totalDeploys: deploys.length,
  avgCoverage:
    Math.round(
      (projects.reduce((sum, p) => sum + p.coverage, 0) / projects.length) * 10,
    ) / 10,
  activeEnvironments: projects.reduce((count, p) => {
    return (
      count +
      Object.values(p.environments).filter((e) => e.status !== "idle").length
    );
  }, 0),
  successRate:
    Math.round(
      (deploys.filter((d) => d.status === "success").length / deploys.length) *
        1000,
    ) / 10,
  buildsStored: buildArtifacts.length,
};

export function formatDate(iso: string): string {
  const date = new Date(iso);
  return date.toLocaleDateString("es-ES", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export function timeAgo(iso: string): string {
  const now = new Date("2026-03-22T14:00:00Z");
  const date = new Date(iso);
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMins / 60);
  const diffDays = Math.floor(diffHours / 24);

  if (diffMins < 60) return `hace ${diffMins}m`;
  if (diffHours < 24) return `hace ${diffHours}h`;
  if (diffDays < 7) return `hace ${diffDays}d`;
  return formatDate(iso);
}
